"""create_wallet_table

Revision ID: 1c96e40149b7
Revises: 
Create Date: 2025-08-13 01:39:57.362857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c96e40149b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('trx_balance', sa.Numeric(), nullable=False),
    sa.Column('bandwidth', sa.Numeric(), nullable=False),
    sa.Column('energy', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_queries_id'), 'wallet_queries', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_queries_wallet_address'), 'wallet_queries', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_queries_wallet_address'), table_name='wallet_queries')
    op.drop_index(op.f('ix_wallet_queries_id'), table_name='wallet_queries')
    op.drop_table('wallet_queries')
    # ### end Alembic commands ###
