"""updated db model

Revision ID: d067c9085b51
Revises: 1c96e40149b7
Create Date: 2025-08-15 14:15:40.451038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd067c9085b51'
down_revision: Union[str, None] = '1c96e40149b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_queries', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('wallet_queries', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_queries', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('wallet_queries', 'updated_at')
    # ### end Alembic commands ###
